#!/usr/bin/env python3
"""Reproduce Supplementary Figure S14 (structural ensemble -> candidate diversity).

Inputs (already generated by run_uniform_2p0.py / rerun_1lvm.py):
  outputs/abl_be_{1CQW,5XJH}_rfd3_bioemu_u10_2p0_s1/tiers/50/designs.fasta   (ensemble: 10 RFD3 + 10 BioEmu @ pure 2.0A gate, 10 seqs/tier)
  outputs/abl_be_{1CQW,5XJH}_single_s1/tiers/50/designs.fasta               (single backbone; 'input' native ref line excluded)

Metric: sequence diversity = 1 - mean pairwise identity (matches/max(len)), an
intensive metric (independent of sample count). Fixed 10-sequence budget drawn
from the pool of K structures, averaged over structure-combinations, draws, and
the 2 targets. Single backbone uses the same fixed-10 budget.

Targets: 1CQW, 5XJH are the enzymes whose full fast-mode default ensemble
(RFD3 10 + BioEmu 10 = 20 structures) passes the production 2.0A fold gate.
(1ATJ/1TCA: only 2 RFD3 pass 2.0A; 1LVM: only 8 BioEmu pass -> excluded.)

Run: /opt/protein_pipeline/venv/bin/python analyze_S14.py
"""
import re, itertools, json, collections
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

OUT = "/opt/protein_pipeline/outputs"
TARGETS = ["1CQW", "5XJH"]
B = 10                       # fixed sequence budget
rng = np.random.default_rng(0)


def meanpair(sl):
    n = len(sl)
    if n < 2:
        return np.nan
    tot = cnt = 0
    for i in range(n):
        a = sl[i]
        for j in range(i + 1, n):
            b = sl[j]; d = max(len(a), len(b), 1)
            m = sum(1 for x, y in zip(a, b) if x == y)
            tot += 1 - m / d; cnt += 1
    return tot / cnt


def by_bb(fa):
    """Ensemble designs grouped by backbone id (source= tag). The ProteinMPNN
    'input' reference line has no backbone= tag and is naturally excluded."""
    bb = collections.defaultdict(lambda: {"src": None, "seqs": []}); h = None; src = None
    for line in open(fa):
        line = line.rstrip("\n")
        if line.startswith(">"):
            m = re.search(r"backbone=([^|]+)\|", line); s = re.search(r"source=([a-z0-9]+)", line)
            h = m.group(1) if m else None; src = s.group(1) if s else None
        elif h and line:
            bb[h]["seqs"].append(line); bb[h]["src"] = src
    return bb


def single_samples(fa):
    """Single-backbone designs, excluding the ProteinMPNN 'input' native reference
    line so the pool definition matches the ensemble arms."""
    out = []; keep = False
    for line in open(fa):
        line = line.rstrip("\n")
        if line.startswith(">"):
            keep = line.startswith(">sample")
        elif keep and line:
            out.append(line)
    return out


ens = {t: by_bb(f"{OUT}/abl_be_{t}_rfd3_bioemu_u10_2p0_s1/tiers/50/designs.fasta") for t in TARGETS}
single = {t: single_samples(f"{OUT}/abl_be_{t}_single_s1/tiers/50/designs.fasta") for t in TARGETS}


def curve(method):
    kmax = min(sum(1 for v in ens[t].values() if method == "combined" or v["src"] == method) for t in TARGETS)
    out = {}
    for K in range(1, kmax + 1):
        vals = []
        for t in TARGETS:
            bbs = [k for k, v in ens[t].items() if method == "combined" or v["src"] == method]
            combos = list(itertools.combinations(bbs, K))
            if len(combos) > 24:
                combos = [tuple(np.array(bbs)[rng.choice(len(bbs), K, replace=False)]) for _ in range(24)]
            tv = []
            for combo in combos:
                pool = [s for k in combo for s in ens[t][k]["seqs"]]
                for _ in range(25):
                    draw = [pool[i] for i in rng.choice(len(pool), min(B, len(pool)), replace=False)]
                    tv.append(meanpair(draw))
            vals.append(np.mean(tv))
        out[K] = float(np.mean(vals))
    return out


res = {m: curve(m) for m in ["rfd3", "bioemu", "combined"]}
sv = []
for t in TARGETS:
    pool = single[t]
    tv = [meanpair([pool[i] for i in rng.choice(len(pool), B, replace=False)]) for _ in range(400)]
    sv.append(np.mean(tv))
single_flat = float(np.mean(sv))

json.dump({**res, "single_flat": single_flat, "targets": TARGETS, "gate": 2.0, "tier": 50, "budget": B},
          open("S14_ensemble_diversity_results.json", "w"), indent=1)

plt.figure(figsize=(7.4, 5.0))
for m, lab, c in [("combined", "RFD3+BioEmu (ensemble)", "#d62728"),
                  ("rfd3", "RFD3 only", "#984ea3"),
                  ("bioemu", "BioEmu only", "#4daf4a")]:
    ks = sorted(res[m]); plt.plot(ks, [res[m][k] for k in ks], "-o", color=c, lw=2.4, ms=5, label=lab)
plt.axhline(single_flat, color="#1f77b4", ls="--", lw=2.2,
            label=f"Single backbone, no ensemble ({single_flat:.2f})")
plt.axvline(20, color="#888", ls=":", lw=1.4)
plt.text(19.6, 0.135, "fast-mode default\n(10 RFD3 + 10 BioEmu)", fontsize=8, ha="right", color="#555")
plt.xticks(range(2, 21, 2)); plt.xlim(0.5, 20.8); plt.ylim(0.10, 0.34)
plt.xlabel("Number of ensemble structures used (K)")
plt.ylabel("Sequence diversity (1 - mean pairwise identity)")
plt.title("Structural ensemble -> diverse candidate pool for surrogate triage\n"
          "(RAPID 2.0A gate; 1CQW/5XJH mean, 50% tier)", fontsize=10.5)
plt.legend(fontsize=9, loc="center right"); plt.grid(alpha=0.3); plt.tight_layout()
plt.savefig("supp_figS14_ensemble_diversity_2p0A.png", dpi=150)
print("wrote supp_figS14_ensemble_diversity_2p0A.png + S14_ensemble_diversity_results.json")
print({m: round(res[m][max(res[m])], 3) for m in res}, "single_flat", round(single_flat, 3))
